services:
  plex:
    cap_drop:
      - ALL
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - VERSION=latest
    volumes:
      - /opt/appdata/plex:/config
      - /mnt/nas/data/media:/media
    devices:
      - /dev/dri:/dev/dri
    ports:
      - "32400:32400"      # main web UI / remote access
      - "1900:1900/udp"    # DLNA
      # GDM network discovery
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    restart: unless-stopped
    networks: [proxy]

  jellyfin:
    cap_drop:
      - ALL
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel  # optional, set to enable hardware acceleration for Intel
    volumes:
      - /opt/appdata/jellyfin:/config
      - /opt/appdata/jellyfin/cache:/cache
      - /mnt/nas/data/media:/media:ro
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 8096:8096
    restart: unless-stopped
    networks: [proxy]

  plexautolanguages:
    cap_drop:
      - ALL
    image: journeyover/plex-auto-languages:latest
    container_name: palang
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - PLEX_URL=http://192.168.1.35:32400/
    env_file:
      - .env
    volumes:
      - /opt/appdata/plexautolanguages:/config
    restart: unless-stopped

  watchstate:
    cap_drop:
      - ALL
    image: ghcr.io/arabcoders/watchstate:latest
    # To change the user/group id associated with the tool change the following line.
    user: "0:0"
    container_name: watchstate
    restart: unless-stopped
    ports:
      - "8082:8080"
    volumes:
      - /opt/appdata/watchstate:/config:rw
    networks: [proxy]

networks:
  proxy:
    external: true
