services:
  adguardhome:
    cap_drop:
      - ALL
    image: adguard/adguardhome
    container_name: adguardhome
    volumes:
      - /opt/appdata/adguard/work:/opt/adguardhome/work
      - /opt/appdata/adguard/conf:/opt/adguardhome/conf
    network_mode: host
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  homebridge:
    cap_drop:
      - ALL
    image: homebridge/homebridge:latest
    container_name: homebridge
    restart: always
    network_mode: host
    volumes:
      - /opt/appdata/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  nginx-proxy-manager:
    cap_drop:
      - ALL
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'    # Public HTTP Port
      - '443:443'  # Public HTTPS Port
      - '81:81'    # Admin Web Port
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /opt/appdata/nginx/data:/data
      - /opt/appdata/nginx/letsencrypt:/etc/letsencrypt
    networks: [proxy]

networks:
  proxy:
    external: true
