services:
  adguardhome:
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - /docker/networking/adguard/work:/opt/adguardhome/work
      - /docker/networking/adguard/conf:/opt/adguardhome/conf
    network_mode: host
    image: adguard/adguardhome

  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - /docker/networking/homebridge/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /docker/networking/nginx/data:/data
      - /docker/networking/nginx/letsencrypt:/etc/letsencrypt
    networks: [proxy]

  crowdsec:
    container_name: crowdsec
    image: crowdsecurity/crowdsec
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    environment:
      COLLECTIONS: "crowdsecurity/nginx"
      GID: "${GID-1000}"
    depends_on:
      - "nginx"
    volumes:
      - ./crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml
      - /docker/networking/nginx/data/logs:/var/log/nginx
      - /docker/networking/crowdsec/data:/var/lib/crowdsec/data/
      - /docker/networking/crowdsec/config:/etc/crowdsec/

networks:
  proxy:
    external: true
